<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction,-Goals-&amp;-Scope" data-toc-modified-id="Introduction,-Goals-&amp;-Scope-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction, Goals &amp; Scope</a></span></li><li><span><a href="#Variable-Explanation" data-toc-modified-id="Variable-Explanation-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Variable Explanation</a></span></li></ul></div>

# Introduction
State notebook purpose here.

## Goals & Methodology
State the goals of the analysis and how it should be done.

## Data and Variable Explanation
Explain the datasets used and the relevant variables.

## Imports
Import libraries and write settings here.

In [1]:
import pandas as pd
import numpy as np

The data cleaning function takes a few minutes to complete.

In [1]:
%run chrisDataCleanFunction.ipynb

time taken to run the function: 157.3311107158661
103.47465085983276

We get the following DFs:

- `salesNew`
- `salesOld`
- `salesNew_nStrata`
- `salesNew_strata`
- `salesNew_total`
- `salesOld_nStrata`
- `salesOld_strata`
- `salesOld_total`
- `rentNew`
- `rentOld`

# Analysis

## Reading & Cleaning data
Read data in and bring it into required structure.

### Master w LGA (KEN)

In [3]:
df1 = pd.read_csv('Files/Cleaned/Master_Pivot_Sales_Rent_5Quarters_Imputed_wFeatures.csv')
df1

,postcode,LGA,mean_price 2020 Q1,mean_price 2020 Q2,mean_price 2020 Q3,mean_price 2020 Q4,mean_price 2021 Q1,median_price 2020 Q1,median_price 2020 Q2,median_price 2020 Q3,...,Rate 2020 Q1,Rate 2020 Q2,Rate 2020 Q3,Rate 2020 Q4,Rate 2021 Q1,constr_index 2020 Q1,constr_index 2020 Q2,constr_index 2020 Q3,constr_index 2020 Q4,constr_index 2021 Q1
0,2000,SYDNEY,1541.0,1322.0,1631.0,1379.0,2794.0,1225.0,1000.0,1390.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
1,2007,SYDNEY,834.0,739.0,658.0,677.0,754.0,745.0,775.0,655.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
2,2008,SYDNEY,956.0,1144.0,985.0,1184.0,937.0,750.0,1173.0,890.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
3,2009,SYDNEY,1277.0,1282.0,1373.0,1661.0,1427.0,986.0,1100.0,1085.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
4,2010,SYDNEY,1357.0,1395.0,1476.0,2267.0,1371.0,1280.0,1325.0,1270.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,2840,CENTRAL DARLING,705.0,725.0,724.0,110.0,760.5,705.0,725.0,724.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
984,2839,BREWARRINA,705.0,725.0,724.0,733.0,760.5,705.0,725.0,724.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
985,2836,CENTRAL DARLING,705.0,725.0,724.0,733.0,760.5,705.0,725.0,724.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
986,2879,CENTRAL DARLING,705.0,725.0,724.0,733.0,760.5,705.0,725.0,724.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8
987,2880,BROKEN HILL,137.0,199.0,132.0,139.0,146.0,125.0,130.0,126.0,...,0.638889,0.25,0.25,0.15625,0.1,116.0,116.2,116.2,116.9,117.8

### Postcode only (KEN)

#### Read and clean

In [10]:
df_pcode = pd.read_csv('Files/Cleaned/Postcode-based/Master_Sales_Rent_2017Q4_2021Q1_pcFeatures.csv')
df_pcode.drop(['skey','rkey','year','quarter'],axis=1,inplace=True)
df_pcode

,postcode,time_period,dwelling_type,median_price,mean_price,sales_no,Qdelta_median,Adelta_median,Qdelta_count,Adelta_count,...,citizen_non_AU,YARRP <1975,YARRP 1976-1995,YARRP 1996-2005,YARRP 2006-2016,ATSI,2yBonds%,10yBonds%,constr_index,Rate
0,2000,2017 Q3,Total,1350.0,1516.328059,135.0,0.1345,0.4746,-0.3250,-0.3112,...,14662.0,525.0,1590.0,2175.0,13023.0,53.0,1.814167,2.646667,112.0,1.5
1,2000,2017 Q3,Strata,1350.0,1516.328059,135.0,0.1431,0.5553,-0.3182,-0.2703,...,14662.0,525.0,1590.0,2175.0,13023.0,53.0,1.814167,2.646667,112.0,1.5
2,2007,2017 Q3,Total,817.5,804.448333,36.0,-0.1090,-0.1572,-0.4462,-0.3455,...,5033.0,109.0,479.0,593.0,4517.0,58.0,1.814167,2.646667,112.0,1.5
3,2007,2017 Q3,Strata,817.5,804.448333,36.0,-0.0815,-0.1528,-0.4194,-0.3208,...,5033.0,109.0,479.0,593.0,4517.0,58.0,1.814167,2.646667,112.0,1.5
4,2008,2017 Q3,Total,995.0,1061.807024,41.0,-0.0005,0.0205,-0.1087,-0.1277,...,5962.0,155.0,541.0,607.0,5527.0,77.0,1.814167,2.646667,112.0,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20585,2748,2021 Q1,Non Strata,843.0,888.000000,5.0,NaN,NaN,NaN,NaN,...,55.0,245.0,124.0,34.0,22.0,25.0,0.090000,1.353333,117.8,0.1
20586,2559,2021 Q1,Total,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,...,275.0,78.0,218.0,171.0,140.0,231.0,0.090000,1.353333,117.8,0.1
20587,2559,2021 Q1,Non Strata,843.0,888.000000,5.0,NaN,NaN,NaN,NaN,...,275.0,78.0,218.0,171.0,140.0,231.0,0.090000,1.353333,117.8,0.1
20588,2588,2021 Q1,Total,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,...,3.0,11.0,8.0,0.0,0.0,17.0,0.090000,1.353333,117.8,0.1
20589,2588,2021 Q1,Non Strata,843.0,888.000000,5.0,NaN,NaN,NaN,NaN,...,3.0,11.0,8.0,0.0,0.0,17.0,0.090000,1.353333,117.8,0.1

In [39]:
trial = df_pcode.loc[df_pcode['dwelling_type']=='Total']
trial.drop(['dwelling_type'],axis=1,inplace=True)
trial.loc[trial.isna().any(axis=1)]

,postcode,time_period,median_price,mean_price,sales_no,Qdelta_median,Adelta_median,Qdelta_count,Adelta_count,median_rent_newb,...,citizen_non_AU,YARRP <1975,YARRP 1976-1995,YARRP 1996-2005,YARRP 2006-2016,ATSI,2yBonds%,10yBonds%,constr_index,Rate
0,2000,2017 Q3,1350.0,1516.328059,135.0,0.1345,0.4746,-0.3250,-0.3112,640.0,...,14662.0,525.0,1590.0,2175.0,13023.0,53.0,1.814167,2.646667,112.0,1.5
2,2007,2017 Q3,817.5,804.448333,36.0,-0.1090,-0.1572,-0.4462,-0.3455,535.0,...,5033.0,109.0,479.0,593.0,4517.0,58.0,1.814167,2.646667,112.0,1.5
4,2008,2017 Q3,995.0,1061.807024,41.0,-0.0005,0.0205,-0.1087,-0.1277,479.0,...,5962.0,155.0,541.0,607.0,5527.0,77.0,1.814167,2.646667,112.0,1.5
7,2009,2017 Q3,1200.0,1434.371014,69.0,0.1811,0.2000,0.2105,0.1311,745.0,...,4142.0,430.0,1201.0,1097.0,3730.0,125.0,1.814167,2.646667,112.0,1.5
10,2010,2017 Q3,1170.0,1241.335294,170.0,-0.0331,0.2348,0.1039,-0.0761,650.0,...,6773.0,1030.0,2203.0,1784.0,6278.0,235.0,1.814167,2.646667,112.0,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20580,2396,2021 Q1,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,450.0,...,23.0,13.0,7.0,4.0,8.0,134.0,0.090000,1.353333,117.8,0.1
20582,2868,2021 Q1,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,450.0,...,11.0,14.0,9.0,3.0,5.0,58.0,0.090000,1.353333,117.8,0.1
20584,2748,2021 Q1,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,450.0,...,55.0,245.0,124.0,34.0,22.0,25.0,0.090000,1.353333,117.8,0.1
20586,2559,2021 Q1,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,510.0,...,275.0,78.0,218.0,171.0,140.0,231.0,0.090000,1.353333,117.8,0.1
20588,2588,2021 Q1,760.5,760.500000,5.0,NaN,NaN,NaN,NaN,450.0,...,3.0,11.0,8.0,0.0,0.0,17.0,0.090000,1.353333,117.8,0.1

In [41]:
trial.dropna()['postcode'].nunique()

451

In [43]:
trial.dropna(inplace=True)
trial

,postcode,time_period,median_price,mean_price,sales_no,Qdelta_median,Adelta_median,Qdelta_count,Adelta_count,median_rent_newb,...,citizen_non_AU,YARRP <1975,YARRP 1976-1995,YARRP 1996-2005,YARRP 2006-2016,ATSI,2yBonds%,10yBonds%,constr_index,Rate
1396,2000,2017 Q4,1315.0,1823.0,183.0,-0.0259,0.0958,0.3456,-0.0758,720.0,...,14662.0,525.0,1590.0,2175.0,13023.0,53.0,1.866667,2.643333,112.5,1.5
1399,2007,2017 Q4,770.0,630.0,20.0,-0.0581,-0.1093,-0.4167,-0.7375,530.0,...,5033.0,109.0,479.0,593.0,4517.0,58.0,1.866667,2.643333,112.5,1.5
1401,2008,2017 Q4,933.0,999.0,20.0,-0.0628,0.0081,-0.3659,-0.4348,478.0,...,5962.0,155.0,541.0,607.0,5527.0,77.0,1.866667,2.643333,112.5,1.5
1404,2009,2017 Q4,1160.0,1421.0,55.0,-0.0333,0.0545,-0.2029,-0.0678,772.5,...,4142.0,430.0,1201.0,1097.0,3730.0,125.0,1.866667,2.643333,112.5,1.5
1407,2010,2017 Q4,1000.0,1108.0,135.0,-0.1507,-0.0909,-0.2151,-0.2932,650.0,...,6773.0,1030.0,2203.0,1784.0,6278.0,235.0,1.866667,2.643333,112.5,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20522,2852,2021 Q1,390.0,411.0,20.0,-0.0602,0.1064,-0.0417,0.4375,355.0,...,75.0,102.0,46.0,16.0,32.0,217.0,0.090000,1.353333,117.8,0.1
20528,2870,2021 Q1,275.0,318.0,69.0,-0.1840,-0.1912,0.0615,0.7692,320.0,...,307.0,221.0,85.0,80.0,260.0,1118.0,0.090000,1.353333,117.8,0.1
20530,2871,2021 Q1,320.0,327.0,40.0,0.0191,0.1228,-0.2857,0.1429,300.0,...,142.0,125.0,77.0,49.0,102.0,1041.0,0.090000,1.353333,117.8,0.1
20532,2877,2021 Q1,195.0,212.0,20.0,-0.0714,0.3636,0.5385,4.0000,220.0,...,91.0,27.0,19.0,8.0,69.0,846.0,0.090000,1.353333,117.8,0.1
20536,2880,2021 Q1,120.0,146.0,107.0,-0.0323,-0.0400,0.1146,0.5070,270.0,...,335.0,292.0,138.0,82.0,265.0,1531.0,0.090000,1.353333,117.8,0.1

In [64]:
unstacked = trial.pivot_table(index='postcode', columns = 'time_period', 
                              values = trial.drop(['postcode','time_period'],axis=1))
unstacked.columns = [' '.join(col) for col in unstacked.columns]
unstacked

,0-4yo 2017 Q4,0-4yo 2018 Q1,0-4yo 2018 Q2,0-4yo 2018 Q3,0-4yo 2018 Q4,0-4yo 2019 Q1,0-4yo 2019 Q2,0-4yo 2019 Q3,0-4yo 2019 Q4,0-4yo 2020 Q1,...,total_bonds_no 2018 Q3,total_bonds_no 2018 Q4,total_bonds_no 2019 Q1,total_bonds_no 2019 Q2,total_bonds_no 2019 Q3,total_bonds_no 2019 Q4,total_bonds_no 2020 Q1,total_bonds_no 2020 Q3,total_bonds_no 2020 Q4,total_bonds_no 2021 Q1
postcode,,,,,,,,,,,,,,,,,,,,,
2000,698.0,698.0,698.0,698.0,698.0,698.0,698.0,698.0,698.0,698.0,...,7457.0,7560.0,7468.0,7946.0,8358.0,8523.0,8615.0,8069.0,9140.0,9327.0
2007,198.0,198.0,198.0,198.0,198.0,198.0,198.0,198.0,198.0,198.0,...,1949.0,1978.0,1980.0,2061.0,2081.0,2058.0,2116.0,1876.0,1979.0,2024.0
2008,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,...,4686.0,4876.0,4685.0,4866.0,4758.0,4798.0,4613.0,4116.0,4514.0,4228.0
2009,606.0,606.0,606.0,606.0,606.0,606.0,606.0,606.0,606.0,606.0,...,2897.0,2904.0,2879.0,2887.0,2900.0,2936.0,2913.0,2913.0,3247.0,3333.0
2010,689.0,689.0,689.0,689.0,689.0,689.0,689.0,689.0,689.0,689.0,...,8248.0,8281.0,8301.0,8289.0,8256.0,8325.0,8338.0,8182.0,8521.0,8626.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2866,NaN,242.0,242.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155.0,157.0,NaN
2870,820.0,820.0,820.0,820.0,820.0,820.0,820.0,820.0,820.0,820.0,...,980.0,965.0,969.0,1000.0,1000.0,986.0,988.0,982.0,989.0,987.0
2871,618.0,618.0,618.0,618.0,618.0,618.0,618.0,618.0,618.0,618.0,...,653.0,663.0,670.0,690.0,700.0,692.0,702.0,733.0,731.0,722.0
2877,324.0,324.0,324.0,NaN,324.0,NaN,NaN,NaN,NaN,NaN,...,NaN,188.0,NaN,NaN,NaN,NaN,NaN,211.0,NaN,204.0
2880,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,...,1646.0,1630.0,1589.0,1616.0,1635.0,1624.0,1616.0,1656.0,1663.0,1667.0

In [76]:
unstacked.isna().sum()

0-4yo 2017 Q4             32
0-4yo 2018 Q1             55
0-4yo 2018 Q2             47
0-4yo 2018 Q3             77
0-4yo 2018 Q4             63
                          ..
total_bonds_no 2019 Q4    53
total_bonds_no 2020 Q1    61
total_bonds_no 2020 Q3    38
total_bonds_no 2020 Q4    35
total_bonds_no 2021 Q1    36
Length: 572, dtype: int64

#### Modeling

In [87]:
unstacked_2 = unstacked.loc[unstacked.notna().all(axis=1)]
unstacked_2

,0-4yo 2017 Q4,0-4yo 2018 Q1,0-4yo 2018 Q2,0-4yo 2018 Q3,0-4yo 2018 Q4,0-4yo 2019 Q1,0-4yo 2019 Q2,0-4yo 2019 Q3,0-4yo 2019 Q4,0-4yo 2020 Q1,...,total_bonds_no 2018 Q3,total_bonds_no 2018 Q4,total_bonds_no 2019 Q1,total_bonds_no 2019 Q2,total_bonds_no 2019 Q3,total_bonds_no 2019 Q4,total_bonds_no 2020 Q1,total_bonds_no 2020 Q3,total_bonds_no 2020 Q4,total_bonds_no 2021 Q1
postcode,,,,,,,,,,,,,,,,,,,,,
2000,698.0,698.0,698.0,698.0,698.0,698.0,698.0,698.0,698.0,698.0,...,7457.0,7560.0,7468.0,7946.0,8358.0,8523.0,8615.0,8069.0,9140.0,9327.0
2007,198.0,198.0,198.0,198.0,198.0,198.0,198.0,198.0,198.0,198.0,...,1949.0,1978.0,1980.0,2061.0,2081.0,2058.0,2116.0,1876.0,1979.0,2024.0
2008,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,...,4686.0,4876.0,4685.0,4866.0,4758.0,4798.0,4613.0,4116.0,4514.0,4228.0
2009,606.0,606.0,606.0,606.0,606.0,606.0,606.0,606.0,606.0,606.0,...,2897.0,2904.0,2879.0,2887.0,2900.0,2936.0,2913.0,2913.0,3247.0,3333.0
2010,689.0,689.0,689.0,689.0,689.0,689.0,689.0,689.0,689.0,689.0,...,8248.0,8281.0,8301.0,8289.0,8256.0,8325.0,8338.0,8182.0,8521.0,8626.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830,2936.0,2936.0,2936.0,2936.0,2936.0,2936.0,2936.0,2936.0,2936.0,2936.0,...,4200.0,4226.0,4256.0,4300.0,4342.0,4336.0,4352.0,4483.0,4517.0,4477.0
2850,1258.0,1258.0,1258.0,1258.0,1258.0,1258.0,1258.0,1258.0,1258.0,1258.0,...,1555.0,1549.0,1589.0,1613.0,1617.0,1598.0,1631.0,1689.0,1662.0,1670.0
2870,820.0,820.0,820.0,820.0,820.0,820.0,820.0,820.0,820.0,820.0,...,980.0,965.0,969.0,1000.0,1000.0,986.0,988.0,982.0,989.0,987.0
2871,618.0,618.0,618.0,618.0,618.0,618.0,618.0,618.0,618.0,618.0,...,653.0,663.0,670.0,690.0,700.0,692.0,702.0,733.0,731.0,722.0
2880,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,1016.0,...,1646.0,1630.0,1589.0,1616.0,1635.0,1624.0,1616.0,1656.0,1663.0,1667.0

In [66]:
list(unstacked.columns)

['0-4yo 2017 Q4',
 '0-4yo 2018 Q1',
 '0-4yo 2018 Q2',
 '0-4yo 2018 Q3',
 '0-4yo 2018 Q4',
 '0-4yo 2019 Q1',
 '0-4yo 2019 Q2',
 '0-4yo 2019 Q3',
 '0-4yo 2019 Q4',
 '0-4yo 2020 Q1',
 '0-4yo 2020 Q3',
 '0-4yo 2020 Q4',
 '0-4yo 2021 Q1',
 '10yBonds% 2017 Q4',
 '10yBonds% 2018 Q1',
 '10yBonds% 2018 Q2',
 '10yBonds% 2018 Q3',
 '10yBonds% 2018 Q4',
 '10yBonds% 2019 Q1',
 '10yBonds% 2019 Q2',
 '10yBonds% 2019 Q3',
 '10yBonds% 2019 Q4',
 '10yBonds% 2020 Q1',
 '10yBonds% 2020 Q3',
 '10yBonds% 2020 Q4',
 '10yBonds% 2021 Q1',
 '15-24yo 2017 Q4',
 '15-24yo 2018 Q1',
 '15-24yo 2018 Q2',
 '15-24yo 2018 Q3',
 '15-24yo 2018 Q4',
 '15-24yo 2019 Q1',
 '15-24yo 2019 Q2',
 '15-24yo 2019 Q3',
 '15-24yo 2019 Q4',
 '15-24yo 2020 Q1',
 '15-24yo 2020 Q3',
 '15-24yo 2020 Q4',
 '15-24yo 2021 Q1',
 '25-34yo 2017 Q4',
 '25-34yo 2018 Q1',
 '25-34yo 2018 Q2',
 '25-34yo 2018 Q3',
 '25-34yo 2018 Q4',
 '25-34yo 2019 Q1',
 '25-34yo 2019 Q2',
 '25-34yo 2019 Q3',
 '25-34yo 2019 Q4',
 '25-34yo 2020 Q1',
 '25-34yo 2020 Q3',
 '25-34yo 2020 Q4',
 '25-34yo 2021 Q1',
 '2yBonds% 2017 Q4',
 '2yBonds% 2018 Q1',
 '2yBonds% 2018 Q2',
 '2yBonds% 2018 Q3',
 '2yBonds% 2018 Q4',
 '2yBonds% 2019 Q1',
 '2yBonds% 2019 Q2',
 '2yBonds% 2019 Q3',
 '2yBonds% 2019 Q4',
 '2yBonds% 2020 Q1',
 '2yBonds% 2020 Q3',
 '2yBonds% 2020 Q4',
 '2yBonds% 2021 Q1',
 '35-54yo 2017 Q4',
 '35-54yo 2018 Q1',
 '35-54yo 2018 Q2',
 '35-54yo 2018 Q3',
 '35-54yo 2018 Q4',
 '35-54yo 2019 Q1',
 '35-54yo 2019 Q2',
 '35-54yo 2019 Q3',
 '35-54yo 2019 Q4',
 '35-54yo 2020 Q1',
 '35-54yo 2020 Q3',
 '35-54yo 2020 Q4',
 '35-54yo 2021 Q1',
 '5-14yo 2017 Q4',
 '5-14yo 2018 Q1',
 '5-14yo 2018 Q2',
 '5-14yo 2018 Q3',
 '5-14yo 2018 Q4',
 '5-14yo 2019 Q1',
 '5-14yo 2019 Q2',
 '5-14yo 2019 Q3',
 '5-14yo 2019 Q4',
 '5-14yo 2020 Q1',
 '5-14yo 2020 Q3',
 '5-14yo 2020 Q4',
 '5-14yo 2021 Q1',
 '55-64yo 2017 Q4',
 '55-64yo 2018 Q1',
 '55-64yo 2018 Q2',
 '55-64yo 2018 Q3',
 '55-64yo 2018 Q4',
 '55-64yo 2019 Q1',
 '55-64yo 2019 Q2',
 '55-64yo 2019 Q3',
 '55-64yo 2019 Q4',
 '55-64yo 2020 Q1',
 '55-64yo 2020 Q3',
 '55-64yo 2020 Q4',
 '55-64yo 2021 Q1',
 '65+yo 2017 Q4',
 '65+yo 2018 Q1',
 '65+yo 2018 Q2',
 '65+yo 2018 Q3',
 '65+yo 2018 Q4',
 '65+yo 2019 Q1',
 '65+yo 2019 Q2',
 '65+yo 2019 Q3',
 '65+yo 2019 Q4',
 '65+yo 2020 Q1',
 '65+yo 2020 Q3',
 '65+yo 2020 Q4',
 '65+yo 2021 Q1',
 'ATSI 2017 Q4',
 'ATSI 2018 Q1',
 'ATSI 2018 Q2',
 'ATSI 2018 Q3',
 'ATSI 2018 Q4',
 'ATSI 2019 Q1',
 'ATSI 2019 Q2',
 'ATSI 2019 Q3',
 'ATSI 2019 Q4',
 'ATSI 2020 Q1',
 'ATSI 2020 Q3',
 'ATSI 2020 Q4',
 'ATSI 2021 Q1',
 'Adelta_count 2017 Q4',
 'Adelta_count 2018 Q1',
 'Adelta_count 2018 Q2',
 'Adelta_count 2018 Q3',
 'Adelta_count 2018 Q4',
 'Adelta_count 2019 Q1',
 'Adelta_count 2019 Q2',
 'Adelta_count 2019 Q3',
 'Adelta_count 2019 Q4',
 'Adelta_count 2020 Q1',
 'Adelta_count 2020 Q3',
 'Adelta_count 2020 Q4',
 'Adelta_count 2021 Q1',
 'Adelta_median 2017 Q4',
 'Adelta_median 2018 Q1',
 'Adelta_median 2018 Q2',
 'Adelta_median 2018 Q3',
 'Adelta_median 2018 Q4',
 'Adelta_median 2019 Q1',
 'Adelta_median 2019 Q2',
 'Adelta_median 2019 Q3',
 'Adelta_median 2019 Q4',
 'Adelta_median 2020 Q1',
 'Adelta_median 2020 Q3',
 'Adelta_median 2020 Q4',
 'Adelta_median 2021 Q1',
 'Adelta_median_rent 2017 Q4',
 'Adelta_median_rent 2018 Q1',
 'Adelta_median_rent 2018 Q2',
 'Adelta_median_rent 2018 Q3',
 'Adelta_median_rent 2018 Q4',
 'Adelta_median_rent 2019 Q1',
 'Adelta_median_rent 2019 Q2',
 'Adelta_median_rent 2019 Q3',
 'Adelta_median_rent 2019 Q4',
 'Adelta_median_rent 2020 Q1',
 'Adelta_median_rent 2020 Q3',
 'Adelta_median_rent 2020 Q4',
 'Adelta_median_rent 2021 Q1',
 'Adelta_new_bonds 2017 Q4',
 'Adelta_new_bonds 2018 Q1',
 'Adelta_new_bonds 2018 Q2',
 'Adelta_new_bonds 2018 Q3',
 'Adelta_new_bonds 2018 Q4',
 'Adelta_new_bonds 2019 Q1',
 'Adelta_new_bonds 2019 Q2',
 'Adelta_new_bonds 2019 Q3',
 'Adelta_new_bonds 2019 Q4',
 'Adelta_new_bonds 2020 Q1',
 'Adelta_new_bonds 2020 Q3',
 'Adelta_new_bonds 2020 Q4',
 'Adelta_new_bonds 2021 Q1',
 'CPRF_2 2017 Q4',
 'CPRF_2 2018 Q1',
 'CPRF_2 2018 Q2',
 'CPRF_2 2018 Q3',
 'CPRF_2 2018 Q4',
 'CPRF_2 2019 Q1',
 'CPRF_2 2019 Q2',
 'CPRF_2 2019 Q3',
 'CPRF_2 2019 Q4',
 'CPRF_2 2020 Q1',
 'CPRF_2 2020 Q3',
 'CPRF_2 2020 Q4',
 'CPRF_2 2021 Q1',
 'CPRF_3 2017 Q4',
 'CPRF_3 2018 Q1',
 'CPRF_3 2018 Q2',
 'CPRF_3 2018 Q3',
 'CPRF_3 2018 Q4',
 'CPRF_3 2019 Q1',
 'CPRF_3 2019 Q2',
 'CPRF_3 2019 Q3',
 'CPRF_3 2019 Q4',
 'CPRF_3 2020 Q1',
 'CPRF_3 2020 Q3',
 'CPRF_3 2020 Q4',
 'CPRF_3 2021 Q1',
 'CPRF_4 2017 Q4',
 'CPRF_4 2018 Q1',
 'CPRF_4 2018 Q2',
 'CPRF_4 2018 Q3',
 'CPRF_4 2018 Q4',
 'CPRF_4 2019 Q1',
 'CPRF_4 2019 Q2',
 'CPRF_4 2019 Q3',
 'CPRF_4 2019 Q4',
 'CPRF_4 2020 Q1',
 'CPRF_4 2020 Q3',
 'CPRF_4 2020 Q4',
 'CPRF_4 2021 Q1',
 'CPRF_5 2017 Q4',
 'CPRF_5 2018 Q1',
 'CPRF_5 2018 Q2',
 'CPRF_5 2018 Q3',
 'CPRF_5 2018 Q4',
 'CPRF_5 2019 Q1',
 'CPRF_5 2019 Q2',
 'CPRF_5 2019 Q3',
 'CPRF_5 2019 Q4',
 'CPRF_5 2020 Q1',
 'CPRF_5 2020 Q3',
 'CPRF_5 2020 Q4',
 'CPRF_5 2021 Q1',
 'CPRF_6+ 2017 Q4',
 'CPRF_6+ 2018 Q1',
 'CPRF_6+ 2018 Q2',
 'CPRF_6+ 2018 Q3',
 'CPRF_6+ 2018 Q4',
 'CPRF_6+ 2019 Q1',
 'CPRF_6+ 2019 Q2',
 'CPRF_6+ 2019 Q3',
 'CPRF_6+ 2019 Q4',
 'CPRF_6+ 2020 Q1',
 'CPRF_6+ 2020 Q3',
 'CPRF_6+ 2020 Q4',
 'CPRF_6+ 2021 Q1',
 'CPRF_HHOLD_NO 2017 Q4',
 'CPRF_HHOLD_NO 2018 Q1',
 'CPRF_HHOLD_NO 2018 Q2',
 'CPRF_HHOLD_NO 2018 Q3',
 'CPRF_HHOLD_NO 2018 Q4',
 'CPRF_HHOLD_NO 2019 Q1',
 'CPRF_HHOLD_NO 2019 Q2',
 'CPRF_HHOLD_NO 2019 Q3',
 'CPRF_HHOLD_NO 2019 Q4',
 'CPRF_HHOLD_NO 2020 Q1',
 'CPRF_HHOLD_NO 2020 Q3',
 'CPRF_HHOLD_NO 2020 Q4',
 'CPRF_HHOLD_NO 2021 Q1',
 'CPRF_na 2017 Q4',
 'CPRF_na 2018 Q1',
 'CPRF_na 2018 Q2',
 'CPRF_na 2018 Q3',
 'CPRF_na 2018 Q4',
 'CPRF_na 2019 Q1',
 'CPRF_na 2019 Q2',
 'CPRF_na 2019 Q3',
 'CPRF_na 2019 Q4',
 'CPRF_na 2020 Q1',
 'CPRF_na 2020 Q3',
 'CPRF_na 2020 Q4',
 'CPRF_na 2021 Q1',
 'INCP_HIGH 2017 Q4',
 'INCP_HIGH 2018 Q1',
 'INCP_HIGH 2018 Q2',
 'INCP_HIGH 2018 Q3',
 'INCP_HIGH 2018 Q4',
 'INCP_HIGH 2019 Q1',
 'INCP_HIGH 2019 Q2',
 'INCP_HIGH 2019 Q3',
 'INCP_HIGH 2019 Q4',
 'INCP_HIGH 2020 Q1',
 'INCP_HIGH 2020 Q3',
 'INCP_HIGH 2020 Q4',
 'INCP_HIGH 2021 Q1',
 'INCP_LOW 2017 Q4',
 'INCP_LOW 2018 Q1',
 'INCP_LOW 2018 Q2',
 'INCP_LOW 2018 Q3',
 'INCP_LOW 2018 Q4',
 'INCP_LOW 2019 Q1',
 'INCP_LOW 2019 Q2',
 'INCP_LOW 2019 Q3',
 'INCP_LOW 2019 Q4',
 'INCP_LOW 2020 Q1',
 'INCP_LOW 2020 Q3',
 'INCP_LOW 2020 Q4',
 'INCP_LOW 2021 Q1',
 'INCP_MID 2017 Q4',
 'INCP_MID 2018 Q1',
 'INCP_MID 2018 Q2',
 'INCP_MID 2018 Q3',
 'INCP_MID 2018 Q4',
 'INCP_MID 2019 Q1',
 'INCP_MID 2019 Q2',
 'INCP_MID 2019 Q3',
 'INCP_MID 2019 Q4',
 'INCP_MID 2020 Q1',
 'INCP_MID 2020 Q3',
 'INCP_MID 2020 Q4',
 'INCP_MID 2021 Q1',
 'INCP_NEG_NIL 2017 Q4',
 'INCP_NEG_NIL 2018 Q1',
 'INCP_NEG_NIL 2018 Q2',
 'INCP_NEG_NIL 2018 Q3',
 'INCP_NEG_NIL 2018 Q4',
 'INCP_NEG_NIL 2019 Q1',
 'INCP_NEG_NIL 2019 Q2',
 'INCP_NEG_NIL 2019 Q3',
 'INCP_NEG_NIL 2019 Q4',
 'INCP_NEG_NIL 2020 Q1',
 'INCP_NEG_NIL 2020 Q3',
 'INCP_NEG_NIL 2020 Q4',
 'INCP_NEG_NIL 2021 Q1',
 'Qdelta_count 2017 Q4',
 'Qdelta_count 2018 Q1',
 'Qdelta_count 2018 Q2',
 'Qdelta_count 2018 Q3',
 'Qdelta_count 2018 Q4',
 'Qdelta_count 2019 Q1',
 'Qdelta_count 2019 Q2',
 'Qdelta_count 2019 Q3',
 'Qdelta_count 2019 Q4',
 'Qdelta_count 2020 Q1',
 'Qdelta_count 2020 Q3',
 'Qdelta_count 2020 Q4',
 'Qdelta_count 2021 Q1',
 'Qdelta_median 2017 Q4',
 'Qdelta_median 2018 Q1',
 'Qdelta_median 2018 Q2',
 'Qdelta_median 2018 Q3',
 'Qdelta_median 2018 Q4',
 'Qdelta_median 2019 Q1',
 'Qdelta_median 2019 Q2',
 'Qdelta_median 2019 Q3',
 'Qdelta_median 2019 Q4',
 'Qdelta_median 2020 Q1',
 'Qdelta_median 2020 Q3',
 'Qdelta_median 2020 Q4',
 'Qdelta_median 2021 Q1',
 'Qdelta_median_rent 2017 Q4',
 'Qdelta_median_rent 2018 Q1',
 'Qdelta_median_rent 2018 Q2',
 'Qdelta_median_rent 2018 Q3',
 'Qdelta_median_rent 2018 Q4',
 'Qdelta_median_rent 2019 Q1',
 'Qdelta_median_rent 2019 Q2',
 'Qdelta_median_rent 2019 Q3',
 'Qdelta_median_rent 2019 Q4',
 'Qdelta_median_rent 2020 Q1',
 'Qdelta_median_rent 2020 Q3',
 'Qdelta_median_rent 2020 Q4',
 'Qdelta_median_rent 2021 Q1',
 'Qdelta_new_bonds 2017 Q4',
 'Qdelta_new_bonds 2018 Q1',
 'Qdelta_new_bonds 2018 Q2',
 'Qdelta_new_bonds 2018 Q3',
 'Qdelta_new_bonds 2018 Q4',
 'Qdelta_new_bonds 2019 Q1',
 'Qdelta_new_bonds 2019 Q2',
 'Qdelta_new_bonds 2019 Q3',
 'Qdelta_new_bonds 2019 Q4',
 'Qdelta_new_bonds 2020 Q1',
 'Qdelta_new_bonds 2020 Q3',
 'Qdelta_new_bonds 2020 Q4',
 'Qdelta_new_bonds 2021 Q1',
 'Rate 2017 Q4',
 'Rate 2018 Q1',
 'Rate 2018 Q2',
 'Rate 2018 Q3',
 'Rate 2018 Q4',
 'Rate 2019 Q1',
 'Rate 2019 Q2',
 'Rate 2019 Q3',
 'Rate 2019 Q4',
 'Rate 2020 Q1',
 'Rate 2020 Q3',
 'Rate 2020 Q4',
 'Rate 2021 Q1',
 'YARRP 1976-1995 2017 Q4',
 'YARRP 1976-1995 2018 Q1',
 'YARRP 1976-1995 2018 Q2',
 'YARRP 1976-1995 2018 Q3',
 'YARRP 1976-1995 2018 Q4',
 'YARRP 1976-1995 2019 Q1',
 'YARRP 1976-1995 2019 Q2',
 'YARRP 1976-1995 2019 Q3',
 'YARRP 1976-1995 2019 Q4',
 'YARRP 1976-1995 2020 Q1',
 'YARRP 1976-1995 2020 Q3',
 'YARRP 1976-1995 2020 Q4',
 'YARRP 1976-1995 2021 Q1',
 'YARRP 1996-2005 2017 Q4',
 'YARRP 1996-2005 2018 Q1',
 'YARRP 1996-2005 2018 Q2',
 'YARRP 1996-2005 2018 Q3',
 'YARRP 1996-2005 2018 Q4',
 'YARRP 1996-2005 2019 Q1',
 'YARRP 1996-2005 2019 Q2',
 'YARRP 1996-2005 2019 Q3',
 'YARRP 1996-2005 2019 Q4',
 'YARRP 1996-2005 2020 Q1',
 'YARRP 1996-2005 2020 Q3',
 'YARRP 1996-2005 2020 Q4',
 'YARRP 1996-2005 2021 Q1',
 'YARRP 2006-2016 2017 Q4',
 'YARRP 2006-2016 2018 Q1',
 'YARRP 2006-2016 2018 Q2',
 'YARRP 2006-2016 2018 Q3',
 'YARRP 2006-2016 2018 Q4',
 'YARRP 2006-2016 2019 Q1',
 'YARRP 2006-2016 2019 Q2',
 'YARRP 2006-2016 2019 Q3',
 'YARRP 2006-2016 2019 Q4',
 'YARRP 2006-2016 2020 Q1',
 'YARRP 2006-2016 2020 Q3',
 'YARRP 2006-2016 2020 Q4',
 'YARRP 2006-2016 2021 Q1',
 'YARRP <1975 2017 Q4',
 'YARRP <1975 2018 Q1',
 'YARRP <1975 2018 Q2',
 'YARRP <1975 2018 Q3',
 'YARRP <1975 2018 Q4',
 'YARRP <1975 2019 Q1',
 'YARRP <1975 2019 Q2',
 'YARRP <1975 2019 Q3',
 'YARRP <1975 2019 Q4',
 'YARRP <1975 2020 Q1',
 'YARRP <1975 2020 Q3',
 'YARRP <1975 2020 Q4',
 'YARRP <1975 2021 Q1',
 'citizen_AU 2017 Q4',
 'citizen_AU 2018 Q1',
 'citizen_AU 2018 Q2',
 'citizen_AU 2018 Q3',
 'citizen_AU 2018 Q4',
 'citizen_AU 2019 Q1',
 'citizen_AU 2019 Q2',
 'citizen_AU 2019 Q3',
 'citizen_AU 2019 Q4',
 'citizen_AU 2020 Q1',
 'citizen_AU 2020 Q3',
 'citizen_AU 2020 Q4',
 'citizen_AU 2021 Q1',
 'citizen_non_AU 2017 Q4',
 'citizen_non_AU 2018 Q1',
 'citizen_non_AU 2018 Q2',
 'citizen_non_AU 2018 Q3',
 'citizen_non_AU 2018 Q4',
 'citizen_non_AU 2019 Q1',
 'citizen_non_AU 2019 Q2',
 'citizen_non_AU 2019 Q3',
 'citizen_non_AU 2019 Q4',
 'citizen_non_AU 2020 Q1',
 'citizen_non_AU 2020 Q3',
 'citizen_non_AU 2020 Q4',
 'citizen_non_AU 2021 Q1',
 'constr_index 2017 Q4',
 'constr_index 2018 Q1',
 'constr_index 2018 Q2',
 'constr_index 2018 Q3',
 'constr_index 2018 Q4',
 'constr_index 2019 Q1',
 'constr_index 2019 Q2',
 'constr_index 2019 Q3',
 'constr_index 2019 Q4',
 'constr_index 2020 Q1',
 'constr_index 2020 Q3',
 'constr_index 2020 Q4',
 'constr_index 2021 Q1',
 'mean_price 2017 Q4',
 'mean_price 2018 Q1',
 'mean_price 2018 Q2',
 'mean_price 2018 Q3',
 'mean_price 2018 Q4',
 'mean_price 2019 Q1',
 'mean_price 2019 Q2',
 'mean_price 2019 Q3',
 'mean_price 2019 Q4',
 'mean_price 2020 Q1',
 'mean_price 2020 Q3',
 'mean_price 2020 Q4',
 'mean_price 2021 Q1',
 'median_price 2017 Q4',
 'median_price 2018 Q1',
 'median_price 2018 Q2',
 'median_price 2018 Q3',
 'median_price 2018 Q4',
 'median_price 2019 Q1',
 'median_price 2019 Q2',
 'median_price 2019 Q3',
 'median_price 2019 Q4',
 'median_price 2020 Q1',
 'median_price 2020 Q3',
 'median_price 2020 Q4',
 'median_price 2021 Q1',
 'median_rent_newb 2017 Q4',
 'median_rent_newb 2018 Q1',
 'median_rent_newb 2018 Q2',
 'median_rent_newb 2018 Q3',
 'median_rent_newb 2018 Q4',
 'median_rent_newb 2019 Q1',
 'median_rent_newb 2019 Q2',
 'median_rent_newb 2019 Q3',
 'median_rent_newb 2019 Q4',
 'median_rent_newb 2020 Q1',
 'median_rent_newb 2020 Q3',
 'median_rent_newb 2020 Q4',
 'median_rent_newb 2021 Q1',
 'new_bonds_no 2017 Q4',
 'new_bonds_no 2018 Q1',
 'new_bonds_no 2018 Q2',
 'new_bonds_no 2018 Q3',
 'new_bonds_no 2018 Q4',
 'new_bonds_no 2019 Q1',
 'new_bonds_no 2019 Q2',
 'new_bonds_no 2019 Q3',
 'new_bonds_no 2019 Q4',
 'new_bonds_no 2020 Q1',
 'new_bonds_no 2020 Q3',
 'new_bonds_no 2020 Q4',
 'new_bonds_no 2021 Q1',
 'population_2016 2017 Q4',
 'population_2016 2018 Q1',
 'population_2016 2018 Q2',
 'population_2016 2018 Q3',
 'population_2016 2018 Q4',
 'population_2016 2019 Q1',
 'population_2016 2019 Q2',
 'population_2016 2019 Q3',
 'population_2016 2019 Q4',
 'population_2016 2020 Q1',
 'population_2016 2020 Q3',
 'population_2016 2020 Q4',
 'population_2016 2021 Q1',
 'sales_no 2017 Q4',
 'sales_no 2018 Q1',
 'sales_no 2018 Q2',
 'sales_no 2018 Q3',
 'sales_no 2018 Q4',
 'sales_no 2019 Q1',
 'sales_no 2019 Q2',
 'sales_no 2019 Q3',
 'sales_no 2019 Q4',
 'sales_no 2020 Q1',
 'sales_no 2020 Q3',
 'sales_no 2020 Q4',
 'sales_no 2021 Q1',
 'total_bonds_no 2017 Q4',
 'total_bonds_no 2018 Q1',
 'total_bonds_no 2018 Q2',
 'total_bonds_no 2018 Q3',
 'total_bonds_no 2018 Q4',
 'total_bonds_no 2019 Q1',
 'total_bonds_no 2019 Q2',
 'total_bonds_no 2019 Q3',
 'total_bonds_no 2019 Q4',
 'total_bonds_no 2020 Q1',
 'total_bonds_no 2020 Q3',
 'total_bonds_no 2020 Q4',
 'total_bonds_no 2021 Q1']

In [90]:
list(unstacked_2.dtypes)

[dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64')]

In [94]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score, KFold

lr = LinearRegression()
score = cross_val_score(lr, unstacked_2.drop(['median_price 2021 Q1'],axis=1), # X
                        unstacked_2['median_price 2021 Q1'],                   # y 
                        cv=KFold(n_splits=10, shuffle=True)) 
score

array([0.97230448, 0.93448869, 0.94661328, 0.4110817 , 0.96210198,
       0.96765441, 0.93759646, 0.9523607 , 0.94677614, 0.93728296])

In [95]:
# from sklearn.model_selection import train_test_split

## Variable Analysis

### Univariate Analysis
Analyse the relevant variables with regards to their distribution, development, outliers, missing values, etc.

### Bivariate Analysis
Analyse possible relationships between target variable and features. Check if features are correlated.

# Modeling

## Baseline Regression Model
Create a first baseline model here.

## Feature Engineering
Improve baseline model with different combinations and/or transformation of variables.

## Improved Model
Test if baseline model can be improved by using more sophisticated algorithms.

# Results

# Conclusion and Outlook
Summarise findings and elaborate on implications and scope of model with regards to data sufficiency.